# 1. Check if uv is already installed (Works on Windows & Linux)
Write-Host "Checking if uv is already installed..." -ForegroundColor Cyan
$uvInstalled = $false

if (Get-Command uv -ErrorAction SilentlyContinue) {
    $uvInstalled = $true
} else {
    # WINDOWS FALLBACK: Check if uv executable exists in the local user profile
    if ($IsWindows -and (Test-Path "$env:USERPROFILE\.local\bin\uv.exe")) {
        $env:Path += ";$env:USERPROFILE\.local\bin"
        $uvInstalled = $true
    # LINUX FALLBACK: Check if uv exists in the user home directory
    } elseif ($IsLinux -and (Test-Path "$env:HOME/.local/bin/uv")) {
        $env:Path += ":$env:HOME/.local/bin"
        $uvInstalled = $true
    }
}

# 2. Install uv only if it is missing
if ($uvInstalled) {
    Write-Host "uv is already installed. Skipping installation part." -ForegroundColor Green
} else {
    # WINDOWS INSTALLATION: Download and execute the native Windows PowerShell script
    if ($IsWindows) {
        Write-Host "uv not found. Installing on Windows..." -ForegroundColor Yellow
        powershell -ExecutionPolicy ByPass -c "irm https://astral.sh | iex"
        $env:Path += ";$env:USERPROFILE\.local\bin"
    # LINUX INSTALLATION: Download and execute the standalone shell script
    } elseif ($IsLinux) {
        Write-Host "uv not found. Installing on Linux..." -ForegroundColor Yellow
        curl -LsSf https://astral.sh | sh
        $env:Path += ":$env:HOME/.local/bin"
    } else {
        Write-Error "Unsupported Operating System."
        Exit 1
    }
}

# 3. Verify uv version
Write-Host "Verifying uv version..." -ForegroundColor Cyan
uv --version

# 4. Create and explicitly activate virtual environment (.venv)
Write-Host "Setting up virtual environment..." -ForegroundColor Cyan
if (-not (Test-Path ".venv")) {
    uv venv
}

# EXPLICIT CROSS-PLATFORM ACTIVATION
if ($IsWindows) {
    Write-Host "Activating virtual environment (Windows)..." -ForegroundColor Cyan
    # WINDOWS: Call the dedicated PowerShell activation script generated by uv
    & .venv\Scripts\Activate.ps1
} else {
    Write-Host "Activating virtual environment (Ubuntu/Linux)..." -ForegroundColor Cyan
    # UBUNTU/LINUX: Dot-source the standard bash activation profile inside pwsh
    . .venv/bin/activate
}

# 5. Install requirements.txt (Works identically on both Windows and Linux)
if (Test-Path "requirements.txt") {
    Write-Host "Installing requirements via uv..." -ForegroundColor Cyan
    uv pip install -r requirements.txt
} else {
    Write-Host "requirements.txt not found. Skipping package installation." -ForegroundColor Yellow
}

# 6. Run app.py via Streamlit (Works identically on both Windows and Linux)
if (Test-Path "app.py") {
    Write-Host "Executing RAG Pipeline via Streamlit..." -ForegroundColor Green
    uv run streamlit run app.py
} else {
    Write-Error "app.py not found in the current directory."
    Exit 1
}
